### ISSUE TITLE
Toggle function?

### ISSUE THREAD

**Issue by Wikunia** [caseyg1204/brackets-quoter#1]
Hi,

maybe you would like to include a toggle function so `'abc' => abc` and `abc => 'abc'`.

**Comment by glepretre** [comment]
This would be great! :+1: :smiley:

**Comment by caseyg1204** [comment]
Thanks for the feedback. I will try to do this today or tomorrow.

**Comment by caseyg1204** [comment]
I decided not to move forward with this project. I just removed the extension from the registry. You can get the behavior provided by this extension by turning on Edit > Auto Close Braces
