### ISSUE TITLE
Extension breaking Brackets auto-closing quotes

### ISSUE THREAD

**Issue by patrickfatrick** [caseyg1204/brackets-quoter#4]
Brackets normally auto-closes quotation marks but this extension breaks that behavior, for both single- and double-quotes. Here's a little video of it happening in HTML, CSS, and JS. http://www.screencast.com/t/8rAMDA0Eq

Seems like a bug to me but maybe this is normal behavior? Uninstalling the extension fixes it, so definitely related to this extension.

**Comment by caseyg1204** [comment]
I just removed the extension from the registry. You can get the behavior by turning on Edit > Auto Close Braces
