### ISSUE TITLE
when I type " it changes it to '

### ISSUE THREAD

**Issue by yahyaKacem** [caseyg1204/brackets-quoter#5]
Hi, I have Ubuntu 14.04 and Brackets (Release 1.2 experimental build 1.2.0-15697) and when I try to use the double quotes it always change it to single quote.
Here's my keyboard layout.
![s](https://cloud.githubusercontent.com/assets/844900/6546737/74c93206-c5bf-11e4-9170-789d3ea822e0.jpg)
when I press the 3 in the top left I get the same as if I press the 4 on the top left.

**Comment by caseyg1204** [comment]
I just removed the extension from the registry. You can get the behavior by turning on Edit > Auto Close Braces
